# Generated by Django 3.0.4 on 2020-04-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now=True)),
                ('author', models.CharField(default='Admin', max_length=32)),
                ('count_message', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('main_text', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('book_ref', models.AutoField(primary_key=True, serialize=False)),
                ('book_date', models.DateField()),
                ('total_amount', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField(null=True)),
                ('price_sale', models.PositiveIntegerField()),
                ('image', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
