# Generated by Django 3.0.4 on 2020-04-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('ticket_no', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_id', models.CharField(max_length=32)),
                ('passenger_name', models.CharField(max_length=64)),
                ('contact_data', models.CharField(max_length=128)),
                ('book_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Bookings')),
            ],
        ),
    ]
