# Generated by Django 3.0.4 on 2020-04-18 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0002_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircrafts',
            fields=[
                ('aircraft_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=32)),
                ('range', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('airport_name', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('coordinates', models.CharField(max_length=128)),
                ('timezone', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_no', models.PositiveIntegerField()),
                ('scheduled_departure', models.DateTimeField()),
                ('scheduled_arrival', models.DateTimeField()),
                ('status', models.CharField(choices=[('вылет по расписанию', 'вылет по расписанию'), ('летит', 'летит'), ('задерживается', 'задерживается'), ('приземлился', 'приземлился')], default='вылет по расписанию', max_length=20)),
                ('actual_departure', models.DateTimeField()),
                ('actual_arrival', models.DateTimeField()),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Aircrafts')),
                ('arrival_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrival_airport', to='airtrans.Airports')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport', to='airtrans.Airports')),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.CharField(max_length=3)),
                ('fare_conditions', models.CharField(choices=[('Эконом-класс', 'Эконом'), ('Бизнес-класс', 'Бизнес-класс')], default='Эконом-класс', max_length=12)),
                ('aircraft_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Aircrafts')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_flights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=1)),
                ('fare_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Seats')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Flights')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Tickets')),
            ],
        ),
        migrations.CreateModel(
            name='Boarding_passes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boarding_no', models.PositiveIntegerField()),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Flights')),
                ('seat_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Seats')),
                ('ticket_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Tickets')),
            ],
        ),
    ]
