# Generated by Django 3.0.4 on 2020-04-18 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0003_aircrafts_airports_boarding_passes_flights_seats_ticket_flights'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boarding_passes',
            unique_together={('ticket_no', 'flight_id')},
        ),
        migrations.AlterUniqueTogether(
            name='seats',
            unique_together={('aircraft_code', 'seat_no')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket_flights',
            unique_together={('ticket_no', 'flight_id')},
        ),
    ]
