# Generated by Django 3.0.4 on 2020-04-18 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0005_auto_20200418_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarding_passes',
            name='flight_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='airtrans.Ticket_flights'),
        ),
    ]
