# Generated by Django 3.0.4 on 2020-04-18 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0007_auto_20200418_2308'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boarding_passes',
            unique_together=set(),
        ),
    ]
