# Generated by Django 3.0.4 on 2020-04-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airtrans', '0009_auto_20200418_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
